apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream-to-bronze
  namespace: nyc-taxi-pipeline
  labels:
    app: stream-to-bronze
    component: ingestion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stream-to-bronze
  template:
    metadata:
      labels:
        app: stream-to-bronze
    spec:
      serviceAccountName: spark
      # Kafka hazır olana kadar başlamayı bekle
      initContainers:
      - name: wait-for-kafka
        image: busybox:1.36
        command:
          - sh
          - -c
          - |
            until nc -z kafka.nyc-taxi-pipeline.svc.cluster.local 9092; do
              echo "Kafka bekleniyor..."; sleep 5
            done
            echo "Kafka hazır, streaming başlatılıyor."
      containers:
      - name: spark-submit-stream-to-bronze
        # CI/CD tarafından ghcr.io/sweiznn yerini IMAGE_REGISTRY alacak
        image: ghcr.io/sweiznn/nyc-taxi-spark:latest
        imagePullPolicy: Always
        command: ["/opt/spark/bin/spark-submit"]
        args: [
          # --deploy-mode client: Bu container driver olarak çalışır.
          # K8s, executor pod'larını otomatik oluşturur.
          "--master", "k8s://https://kubernetes.default.svc",
          "--deploy-mode", "client",
          "--name", "stream-to-bronze",
          "--conf", "spark.kubernetes.namespace=nyc-taxi-pipeline",
          "--conf", "spark.kubernetes.container.image=ghcr.io/sweiznn/nyc-taxi-spark:latest",
          "--conf", "spark.kubernetes.authenticate.driver.serviceAccountName=spark",
          "--conf", "spark.executor.instances=1",
          "local:///app/spark_jobs/stream_to_bronze.py"
        ]
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka.nyc-taxi-pipeline.svc.cluster.local:9092"
        - name: KAFKA_TOPIC
          value: "yellow_taxi_trips"
        - name: DELTA_BRONZE_PATH
          value: "/data/delta/bronze/yellow_taxi_trips"
        - name: BRONZE_CHECKPOINT_PATH
          value: "/data/delta/checkpoints/bronze_yellow_taxi_trips"
        - name: BRONZE_STARTING_OFFSETS
          value: "earliest"
        volumeMounts:
        - name: spark-data
          mountPath: /data
      volumes:
      - name: spark-data
        persistentVolumeClaim:
          claimName: spark-data-pvc


