apiVersion: batch/v1
kind: Job
metadata:
  name: silver-to-gold-job
  namespace: nyc-taxi-pipeline
  labels:
    app: silver-to-gold
    component: processing
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      serviceAccountName: spark
      containers:
      - name: spark-submit-silver-to-gold
        # CI/CD tarafından ghcr.io/sweiznn yerini IMAGE_REGISTRY alacak
        image: ghcr.io/sweiznn/nyc-taxi-spark:latest
        imagePullPolicy: Always
        command: ["/opt/spark/bin/spark-submit"]
        args: [
          "--master", "k8s://https://kubernetes.default.svc",
          "--deploy-mode", "client",
          "--name", "silver-to-gold",
          "--conf", "spark.kubernetes.namespace=nyc-taxi-pipeline",
          "--conf", "spark.kubernetes.container.image=ghcr.io/sweiznn/nyc-taxi-spark:latest",
          "--conf", "spark.kubernetes.authenticate.driver.serviceAccountName=spark",
          "--conf", "spark.executor.instances=1",
          "local:///app/spark_jobs/silver_to_gold.py"
        ]
        env:
        - name: DELTA_SILVER_PATH
          value: "/data/delta/silver/yellow_taxi_trips"
        - name: DELTA_GOLD_PATH
          value: "/data/delta/gold/fare_features"
        volumeMounts:
        - name: spark-data
          mountPath: /data
      volumes:
      - name: spark-data
        persistentVolumeClaim:
          claimName: spark-data-pvc
      restartPolicy: Never
  backoffLimit: 1


